{{- if or .Values.gateway.apiKey .Values.gateway.license.key .Values.gateway.database.dbUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-config
  labels: {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.gateway.apiKey }}
  GATEWAY_API_KEY: {{ .Values.gateway.apiKey | quote }}
  {{- end }}
  {{- if .Values.gateway.license.key }}
  AEGIS_LICENSE_KEY: {{ .Values.gateway.license.key | quote }}
  {{- end }}
  {{- if .Values.gateway.database.dbUrl }}
  DB_URL: {{ .Values.gateway.database.dbUrl | quote }}
  {{- end }}
{{- end }}
